/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ciccancer.apid.cytoscapeapp.gui;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.Icon;
import org.cytoscape.application.swing.CytoPanelComponent;
import org.cytoscape.application.swing.CytoPanelName;
import org.cytoscape.model.CyNetworkFactory;
import org.cytoscape.model.CyNetworkManager;
import org.cytoscape.service.util.CyServiceRegistrar;
import org.cytoscape.view.layout.CyLayoutAlgorithmManager;
import org.cytoscape.view.model.CyNetworkViewFactory;
import org.cytoscape.view.model.CyNetworkViewManager;

/**
 *
 * @author miguelangelgutierrezgarcia
 */
public class MainAPIDPanel extends javax.swing.JPanel implements CytoPanelComponent {

    /**
     * Creates new form Panel
     */
    public MainAPIDPanel(CyNetworkFactory cyNetworkFactoryServiceRef, CyNetworkManager netMgr, CyNetworkViewFactory cnvf, 
            CyNetworkViewManager networkViewManager, CyLayoutAlgorithmManager layoutManager, CyServiceRegistrar registrar) {
        initComponents();
        SearchPanel sp = new SearchPanel(cyNetworkFactoryServiceRef, netMgr, cnvf, networkViewManager, layoutManager, registrar);
        this.add(sp,BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public CytoPanelName getCytoPanelName() {
        return CytoPanelName.WEST;
    }

    @Override
    public String getTitle() {
        return "APID";
    }

    @Override
    public Icon getIcon() {
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
